### ISSUE TITLE
Unable to compile Go package

### ISSUE THREAD

**Issue by guneemwelloeux** [Keysight/clipsgo#1]
After retrieving the package with `go get github.com/keysight/clipsgo`, I tried to build the whole package, and got the following error:
```
go build -o clipsgo ./cmd/clipsgo
# github.com/keysight/clipsgo/pkg/clips
pkg/clips/callback.go:5:11: fatal error: clips/clips.h: No such file or directory
    5 | // #include <clips/clips.h>
      |           ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:38: clipsgo] Error 2
```

The compilation of clips itself went fine, and the sources are available in `go/src/github.com/keysight/clipsgo/clips_source`

I'm using `go version go1.13.8 linux/amd64` on Ubuntu 20.04 LTS.

Thanks

**Comment by guneemwelloeux** [comment]
Taking `callback.go` as an example. The 3 cgo lines show:
```
// #cgo CFLAGS: -I ../../clips_source
// #cgo LDFLAGS: -L ../../clips_source -l clips -lm                                                                     
// #include "clips/clips.h"                                                                                             
```
It seems that it won't work, because `../../clips_source` resolves to `$GOPATH/src/github.com/keysight/clipsgo/clips_source`, in that folder, there is no `clips` folder.

So either the `-I` flag is wrong, or the `include` is wrong.

However, no matter how I tried to modify these, to point to the actual `clips.h` file, I couldn't get it to compile with `go tool cgo callback.go`.

It looks like the `-I` flag is completely ignored.

I finally got the compilation to work properly by pointing the include directly to the actual file:
```
~ // #cgo LDFLAGS: -L ../../clips_source -l clips -lm                                                                     
~ // #include "../../clips_source/clips.h"                                                                                
```

Is cgo broken? or is the directive not the correct one?

**Comment by guneemwelloeux** [comment]
I was able to finally compile using `go version go1.16.2 linux/amd64`, and changing the `CFLAGS` in `callback.go`, as well as adding a `clips` symlink to `clips_source` in the clipsgo directory.
```
// #cgo CFLAGS: -I ../..
```

**Comment by kraney** [comment]
Unfortunately I have changed jobs and no longer have maintenance rights on this repo.

I was able to build without modifications, but I obtained the repo with `git clone` rather than `go get`. Not sure if that might be the difference.

**Comment by guneemwelloeux** [comment]
Hello @kraney 

I'm still experiencing compilation issues, unfortunately.

Here is what I tried today (Note that I'm only assuming that this is the way to build, as the README does not explicitely tell how this step should be done)

```
~$ git clone ssh://git@github.com/keysight/clipsgo.git
~$ cd clipsgo
~/clipsgo$ make
```

Again, I'm still getting the same error:
```
...[successful compilation lines redacted]
gcc -o clips main.o -L. -lclips -lm -lrt
make[1]: Leaving directory '/home/pollux/clipsgo/clips_source'
ld -G clips_source/*.o -o clips_source/libclips.so
go build -o clipsgo ./cmd/clipsgo
# github.com/keysight/clipsgo/pkg/clips
pkg/clips/callback.go:5:11: fatal error: clips/clips.h: No such file or directory
    5 | // #include <clips/clips.h>
      |           ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:38: clipsgo] Error 2
```

The sources of clips are properly downloaded by the make process, and the clips shared lib `libclips.so` is built successfully.
The only step that seems to fail is the go compilation itself. And it all seems logical to me, given the `CFLAGS` specified in the go files.

Also note that I don't have clips installed on my system, so I'm solely relying on the make process to use whatever sources are being downloaded.

@Keysight: Is this project dead? If not, could you please let me know who the maintainer is?

**Comment by mattsmi** [comment]
I have forked the repository as it does not seem to be maintained by the original author.
Go [here](https://github.com/mattsmi/clipsgo) to find a working version, including instructions for building the executable or using *clipsgo* in your own Go code.
